//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Document = newDocumentTable()

type DocumentTable struct {
	mysql.Table

	//Columns
	ID      mysql.ColumnInteger
	Name    mysql.ColumnString
	Content mysql.ColumnString
	Type    mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

// AS creates new DocumentTable with assigned alias
func (a *DocumentTable) AS(alias string) DocumentTable {
	aliasTable := newDocumentTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newDocumentTable() DocumentTable {
	var (
		IDColumn       = mysql.IntegerColumn("id")
		NameColumn     = mysql.StringColumn("name")
		ContentColumn  = mysql.StringColumn("content")
		TypeColumn     = mysql.StringColumn("type")
		allColumns     = mysql.ColumnList{IDColumn, NameColumn, ContentColumn, TypeColumn}
		mutableColumns = mysql.ColumnList{NameColumn, ContentColumn, TypeColumn}
	)

	return DocumentTable{
		Table: mysql.NewTable("test", "document", allColumns...),

		//Columns
		ID:      IDColumn,
		Name:    NameColumn,
		Content: ContentColumn,
		Type:    TypeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
