//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Posts = newPostsTable()

type PostsTable struct {
	mysql.Table

	//Columns
	ID      mysql.ColumnInteger
	OwnerID mysql.ColumnInteger
	Text    mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

// AS creates new PostsTable with assigned alias
func (a *PostsTable) AS(alias string) PostsTable {
	aliasTable := newPostsTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPostsTable() PostsTable {
	var (
		IDColumn       = mysql.IntegerColumn("id")
		OwnerIDColumn  = mysql.IntegerColumn("owner_id")
		TextColumn     = mysql.StringColumn("text")
		allColumns     = mysql.ColumnList{IDColumn, OwnerIDColumn, TextColumn}
		mutableColumns = mysql.ColumnList{OwnerIDColumn, TextColumn}
	)

	return PostsTable{
		Table: mysql.NewTable("test", "posts", allColumns...),

		//Columns
		ID:      IDColumn,
		OwnerID: OwnerIDColumn,
		Text:    TextColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
