//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Users = newUsersTable()

type UsersTable struct {
	mysql.Table

	//Columns
	ID           mysql.ColumnInteger
	Name         mysql.ColumnString
	Username     mysql.ColumnString
	PasswordHash mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

// AS creates new UsersTable with assigned alias
func (a *UsersTable) AS(alias string) UsersTable {
	aliasTable := newUsersTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newUsersTable() UsersTable {
	var (
		IDColumn           = mysql.IntegerColumn("id")
		NameColumn         = mysql.StringColumn("name")
		UsernameColumn     = mysql.StringColumn("username")
		PasswordHashColumn = mysql.StringColumn("password_hash")
		allColumns         = mysql.ColumnList{IDColumn, NameColumn, UsernameColumn, PasswordHashColumn}
		mutableColumns     = mysql.ColumnList{NameColumn, UsernameColumn, PasswordHashColumn}
	)

	return UsersTable{
		Table: mysql.NewTable("test", "users", allColumns...),

		//Columns
		ID:           IDColumn,
		Name:         NameColumn,
		Username:     UsernameColumn,
		PasswordHash: PasswordHashColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
