//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var DocumentType = &struct {
	Pdf   mysql.StringExpression
	Docx  mysql.StringExpression
	Jpg   mysql.StringExpression
	Png   mysql.StringExpression
	Pages mysql.StringExpression
	Odt   mysql.StringExpression
	Txt   mysql.StringExpression
	HTML  mysql.StringExpression
	Gif   mysql.StringExpression
	Mpeg  mysql.StringExpression
	Mp3   mysql.StringExpression
	Aac   mysql.StringExpression
	Ai    mysql.StringExpression
}{
	Pdf:   mysql.NewEnumValue("pdf"),
	Docx:  mysql.NewEnumValue("docx"),
	Jpg:   mysql.NewEnumValue("jpg"),
	Png:   mysql.NewEnumValue("png"),
	Pages: mysql.NewEnumValue("pages"),
	Odt:   mysql.NewEnumValue("odt"),
	Txt:   mysql.NewEnumValue("txt"),
	HTML:  mysql.NewEnumValue("html"),
	Gif:   mysql.NewEnumValue("gif"),
	Mpeg:  mysql.NewEnumValue("mpeg"),
	Mp3:   mysql.NewEnumValue("mp3"),
	Aac:   mysql.NewEnumValue("aac"),
	Ai:    mysql.NewEnumValue("ai"),
}
